# Generated by Django 3.0.3 on 2020-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meigennapp', '0002_remove_meigennmodel_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigennmodel',
            name='age',
            field=models.CharField(choices=[('令和', '令和'), ('平成', '平成'), ('昭和', '昭和'), ('大正', '大正'), ('明治', '明治')], max_length=50),
        ),
    ]
